export shared from './shared'
export home from './home'
export result from './result'
export success from './success'
export detail from './detail'
export want from './want'
export collocation from './collocation'
export vote from './vote'
